name = "Signal"
license = "MIT"
licenselink = "https://github.com/haircut/signal/blob/master/LICENSE"
description = ""
homepage = ""
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Matthew Warren"
  homepage = "https://haircut.blog/"
